CREATE TABLE VENDORS (
	ID NUMBER(8) PRIMARY KEY NOT NULL,
	NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE MEASURES (
	ID NUMBER(8) PRIMARY KEY NOT NULL,
	NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE PRODUCTS (
	ID NUMBER(8) PRIMARY KEY NOT NULL,
	VENDORID NUMBER(8) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	MEASUREID NUMBER(8) NOT NULL,
	PRICE NUMBER(8) NOT NULL,
  CONSTRAINT FK_PRODUCTS_VENDOR FOREIGN KEY (VENDORID) REFERENCES VENDORS(ID),
  CONSTRAINT FK_PRODUCTS_MEASURE FOREIGN KEY (MEASUREID) REFERENCES MEASURES(ID)
);

CREATE TABLE SUPERMARKETS (
	ID NUMBER(8) PRIMARY KEY NOT NULL,
	NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE SUPERMARKETS_PRODUCTS (
	SUPERMARKETID NUMBER(8) NOT NULL,
	PRODUCTID NUMBER(8) NOT NULL,
  CONSTRAINT FK_S_P_S FOREIGN KEY (SUPERMARKETID) REFERENCES SUPERMARKETS(ID),
  CONSTRAINT FK_S_P_P FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
	CONSTRAINT PK_SUPERMARKETS_PRODUCTS PRIMARY KEY(SUPERMARKETID, PRODUCTID)
);

INSERT ALL
INTO VENDORS (ID, Name) VALUES (1, 'Unipek Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (2, 'Kaliakra Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (3, 'Deroni Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (4, 'Tandem Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (5, 'Sachi Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (6, 'Leki Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (7, 'Gradus Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (8, 'Olimpus International LTD')
INTO VENDORS (ID, Name) VALUES (9, 'Madzharov Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (10, 'Milka International LTD')
INTO VENDORS (ID, Name) VALUES (11, 'Sushard International LTD')
INTO VENDORS (ID, Name) VALUES (12, 'Rois Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (13, 'Zagorka Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (14, 'Kamenitza Bulgaria LTD')
INTO VENDORS (ID, Name) VALUES (15, 'Pirinsko Bulgaria LTD')
SELECT * FROM DUAL;

INSERT ALL
INTO MEASURES (ID, Name) VALUES (1, 'kg')
INTO MEASURES (ID, Name) VALUES (2, 'g')
INTO MEASURES (ID, Name) VALUES (3, 'l')
INTO MEASURES (ID, Name) VALUES (4, 'ml')
INTO MEASURES (ID, Name) VALUES (5, 'pieces')
SELECT * FROM DUAL;

INSERT ALL
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (1, 1, 'White bread', 5, 1.20)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (2, 1, 'Wheet bread', 5, 1.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (3, 1, 'Holegrain bread', 5, 1.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (4, 2, 'Cooking oil', 3, 2.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (5, 2, 'Margarine', 5, 4.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (6, 3, 'Chutney', 5, 3.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (7, 3, 'Ketchup', 5, 2.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (8, 4, 'Ham', 1, 15.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (9, 4, 'Tandem Sausages', 1, 9.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (10, 5, 'Sachi Sausages', 1, 7.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (11, 6, 'Leki Sausages', 1, 6.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (12, 7, 'Chiken', 1, 5.50)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (13, 7, 'Chicken drumsticks', 1, 7.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (14, 7, 'Chicken wings', 1, 6.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (15, 8, 'Olimpus white cheese', 1, 12.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (16, 8, 'Olimpus yellow cheese', 1, 18.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (17, 9, 'Madzharov white cheese', 1, 10.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (18, 9, 'Madzharov yellow cheese', 1, 16.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (19, 10, 'Milka kids chockolate', 1, 2.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (20, 11, 'Shushard dark chocolate', 1, 1.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (21, 12, 'Almonds', 1, 5.50)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (22, 12, 'Hazelnuts', 1, 4.50)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (23, 12, 'Cashew', 1, 5.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (24, 13, 'Zagorka beer', 1, 1.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (25, 14, 'Kamenitza beer', 1, 1.00)
INTO PRODUCTS (ID, VENDORID, Name, MEASUREID, PRICE) VALUES (26, 15, 'Pirinsko beer', 1, 1.00)
SELECT * FROM DUAL;

INSERT ALL
INTO SUPERMARKETS (ID, Name) VALUES (1, 'Dar Banishora')
INTO SUPERMARKETS (ID, Name) VALUES (2, 'Dar Ovcha Kupel')
INTO SUPERMARKETS (ID, Name) VALUES (3, 'Dar Beli Brezi')
INTO SUPERMARKETS (ID, Name) VALUES (4, 'Dar Mladost')
INTO SUPERMARKETS (ID, Name) VALUES (5, 'Dar Lyulin')
SELECT * FROM DUAL;

INSERT ALL
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 1)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 1)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 1)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 1)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 1)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 2)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 2)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 2)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 2)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 2)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 3)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 3)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 3)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 3)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 3)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 4)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 4)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 4)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 4)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 4)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 5)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 5)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 5)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 5)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 5)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 6)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 6)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 6)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 6)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 6)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 7)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 7)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 7)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 7)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 7)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 8)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 8)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 8)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 8)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 8)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 9)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 9)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 9)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 9)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 9)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 10)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 10)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 10)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 10)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 10)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 11)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 11)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 11)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 11)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 11)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 12)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 12)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 12)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 12)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 12)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 13)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 13)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 13)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 13)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 13)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 14)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 14)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 14)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 14)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 14)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 15)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 15)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 15)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 15)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 15)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 16)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 16)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 16)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 16)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 16)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 17)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 17)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 17)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 17)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 17)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 18)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 18)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 18)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 18)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 18)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 19)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 19)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 19)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 19)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 19)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 20)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 20)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 20)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 20)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 20)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 21)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 21)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 21)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 21)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 21)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 22)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 22)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 22)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 22)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 22)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 23)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 23)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 23)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 23)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 23)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 24)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 24)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 24)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 24)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 24)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 25)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 25)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 25)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 25)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 25)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (1, 26)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (2, 26)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (3, 26)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (4, 26)
INTO SUPERMARKETS_PRODUCTS (SUPERMARKETID, PRODUCTID) VALUES (5, 26)
SELECT * FROM DUAL;

/*
DROP TABLE SUPERMARKETS_PRODUCTS;
DROP TABLE PRODUCTS;
DROP TABLE MEASURES;
DROP TABLE SUPERMARKETS;
DROP TABLE VENDORS;
*/
