//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketChain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.SUPERMARKETS = new HashSet<SUPERMARKETS>();
        }
    
        public int ID { get; set; }
        public int VENDORID { get; set; }
        public string NAME { get; set; }
        public int MEASUREID { get; set; }
        public int PRICE { get; set; }
    
        public virtual MEASURES MEASURES { get; set; }
        public virtual VENDORS VENDORS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPERMARKETS> SUPERMARKETS { get; set; }
    }
}
