//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketsChain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public Expens()
        {
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int Id { get; set; }
        public System.DateTime Month { get; set; }
        public decimal Expense { get; set; }
    
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
